In [2]:
# Import dependencies
import matplotlib.pyplot as plt
import requests
import pandas as pd
from config import api_key
from config import g_key
import gmaps

# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Import file from Part 1, and read into a dataframe
weather_data_df = pd.read_csv("../WeatherPy/OutputData/cities_weather_data.csv")
weather_data_df

,City,Latitude,Longitude,Max Temp.,Humidity,Cloudiness,Wind Speed,Country,Date,Date Converted
0,chokurdakh,70.6333,147.9167,15.76,85,100,11.59,RU,1618867809,2021-04-19 21:30:09
1,victoria,22.2855,114.1577,72.00,78,97,20.71,HK,1618867696,2021-04-19 21:28:16
2,butaritari,3.0707,172.7902,83.12,76,95,13.31,KI,1618867809,2021-04-19 21:30:09
3,atuona,-9.8000,-139.0333,80.20,78,21,18.63,PF,1618867810,2021-04-19 21:30:10
4,puerto rondon,6.2805,-71.1000,87.35,47,100,7.58,CO,1618867810,2021-04-19 21:30:10
...,...,...,...,...,...,...,...,...,...,...
564,taoudenni,22.6783,-3.9836,83.59,11,0,10.42,ML,1618868052,2021-04-19 21:34:12
565,neyshabur,36.2133,58.7958,60.73,42,3,1.21,IR,1618868052,2021-04-19 21:34:12
566,itamaraju,-17.0392,-39.5311,73.42,94,86,4.94,BR,1618868053,2021-04-19 21:34:13
567,ciamis,-7.3257,108.3534,72.34,94,92,1.01,ID,1618868053,2021-04-19 21:34:13
568,chapais,49.7834,-74.8492,53.60,30,75,3.44,CA,1618868054,2021-04-19 21:34:14

In [ ]:
# Create heatmap for data depending on humidity
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
cities = weather_data_df[["Latitude", "Longitude"]].astype(float)

heat_layer = gmaps.heatmap_layer(cities, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

# Create a gmaps figure
fig = gmaps.figure(layout=figure_layout)
fig.add_layer(heat_layer)
fig

In [5]:
# Create dataframe for locations with ideal conditions
weather_data_ideal = weather_data_df.loc[(weather_data_df["Max Temp."] > 70) & (weather_data_df["Max Temp."] < 80) & 
                                        (weather_data_df["Wind Speed"] <= 10) & (weather_data_df["Cloudiness"] <= 0), :]
weather_data_ideal

,City,Latitude,Longitude,Max Temp.,Humidity,Cloudiness,Wind Speed,Country,Date,Date Converted
74,pafos,34.7667,32.4167,73.40,43,0,2.30,CY,1618867838,2021-04-19 21:30:38
82,chino valley,34.7575,-112.4538,75.00,12,0,4.00,US,1618867841,2021-04-19 21:30:41
146,chabahar,25.2919,60.6430,78.76,66,0,9.35,IR,1618867866,2021-04-19 21:31:06
242,buraydah,26.3260,43.9750,78.80,29,0,5.75,SA,1618867826,2021-04-19 21:30:26
273,dalkola,25.8500,87.8500,74.10,52,0,8.16,IN,1618867915,2021-04-19 21:31:55
295,karratha,-20.7377,116.8463,76.33,51,0,9.19,AU,1618867754,2021-04-19 21:29:14
312,san clemente,33.4270,-117.6120,72.00,68,0,1.99,US,1618867811,2021-04-19 21:30:11

In [ ]:
# Create markers on heatmap for hotel locations
marker_locations = weather_data_ideal[['Latitude', 'Longitude']]